# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7fdfdb7ef379e7cbcd51242998e3f1f75614ee99d1d408e8b278205ffdfaa984658ec15e3056b2edf2104bd709bac0c967c5ab76e5d0b9eb5ba13db2af4e638

test:
  secret_key_base: cd64a5e4af30b3944a8a977252f5c2bb844560c8d319e783f708661d35f580c70379dc65af836a2d92e7d92e22215df569a3ae54b0308691462b7b1185de410c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
